---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-step-one
  annotations:
    # This tells crossplane beta render to connect to the function locally.
    render.crossplane.io/runtime: Development
# spec:
  # This is ignored when using the Development runtime.
  # package: function-template-go
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-step-two
  annotations:
    # This tells crossplane beta render to connect to the function locally.
    render.crossplane.io/runtime: Development
    render.crossplane.io/runtime-development-target: localhost:8081
# spec:
#   # This is ignored when using the Development runtime.
#   package: function-template-go
